[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "talos-te-sbjat"
authors = [
    {name = "Will Koester", email = "wikoeste@cisco.com"}
]
description = "SBRS Jira Automation Tool"
version = "1.6.6"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "os",
    "sys",
    "dns",
    "ipaddress",
    "re",
    "shlex",
    "socket",
    "subprocess",
    "threading",
    "time",
    "jira",
    "getpass",
    "json",
    "ipaddress",
    "IPv4Address",
    "netaddr",
    "queue"
]

[project.scripts]
talos-te-sbjat = "sbjat:main"

